blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djangopress.blog.urls', 'djangopress', 'djangopress')),
]

djangopress/blog/urls.py
"""Djangopress' Urls """
from django.conf.urls import url, include

from .views import PostList, PostDetail, MonthArchive

app_name = 'djangopress'  # pylint: disable=invalid-name
urlpatterns = [
    url(r'^', include('djangopress.pages.urls')),
    url(r'^$', PostList.as_view(), name='home'),
    url(r'^page/(?P<page>[\d]+)/$', PostList.as_view(), name='page'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        MonthArchive.as_view(),
        name="month_archive"
        ),
    url(r'^post/(?P<slug>[\w\d-]+)/$', PostDetail.as_view(), name='post'),
]

djangopress/pages/urls.py
"""Pages' URLs."""
from django.conf.urls import url

from .views import PageDetail


urlpatterns = [
    url(r'^(?P<slug>[\w\d-]+)/$', PageDetail.as_view(), name='page'),
]

djangopress/blog/models.py
"""Blog models."""
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.conf import settings
from django.utils.timezone import now
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify


@python_2_unicode_compatible
class Post(models.Model):
    """Post Model."""

    STATUS_CHOICES = (('D', 'Draft'),
                      ('PB', 'Public'),
                      ('PV', 'Private'),
                      ('T', 'Trash'),
                      )

    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE
                               )
    title = models.CharField(max_length=100, blank=True, null=True)
    slug = models.SlugField(max_length=100, blank=True)
    content = models.TextField(blank=True, null=True)
    excerpt = models.TextField(blank=True, null=True)
    featured_image = models.ImageField(upload_to='post_covers',
                                       blank=True,
                                       null=True
                                       )
    creation_date = models.DateTimeField(blank=True, default=now)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    modified_date = models.DateTimeField(editable=False)
    category = models.ManyToManyField('Category',
                                      blank=True
                                      )

    @property
    def get_absolute_url(self):
        """Get the absolute url of a post"""
        return reverse('djangopress:post', kwargs={'slug': self.slug})

    def __str__(self):
        """String representation of Post object"""
        return self.title or 'No title'

    def save(self, *args, **kwargs):
        """Save the Post object and create a slug"""
        if self.title and not self.slug:
            self.slug = slugify(self.title)
        elif self.slug:
            self.slug = self.slug
        else:
            assert ValueError
        self.modified_date = now()
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-creation_date']


@python_2_unicode_compatible
class Category(models.Model):
    """Category model."""
    name = models.CharField(max_length=255)
    parent = models.ForeignKey('self',
                               on_delete=models.CASCADE,
                               blank=True,
                               null=True,
                               )

    def __str__(self):
        """Category string representation."""
        return self.name

djangopress/comments/models.py
"""Models for the comments app."""
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.utils.timezone import now

from djangopress.blog.models import Post


@python_2_unicode_compatible
class Comment(models.Model):
    """Comment model."""
    content = models.TextField()
    author = models.CharField(max_length=255)
    author_email = models.EmailField()
    author_website = models.URLField(blank=True, null=True)
    creation_date = models.DateTimeField(default=now)
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE
                             )

    def __str__(self):
        return '%s on %s' % (self.author, self.post)

djangopress/core/models.py
"""Djangopress models."""
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models


@python_2_unicode_compatible
class Option(models.Model):
    """Option."""
    name = models.CharField(unique=True, max_length=255)
    value = models.CharField(max_length=255)

    def __str__(self):
        """String representation of Option object"""
        return self.name

djangopress/menus/models.py
"""Models for menu app."""
from __future__ import unicode_literals
import re
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse, NoReverseMatch


@python_2_unicode_compatible
class Menu(models.Model):
    """Menu model."""
    name = models.CharField(max_length=255)

    def __str__(self):
        """String representation of Menu."""
        return self.name


@python_2_unicode_compatible
class MenuItem(models.Model):
    """MenuItem model."""
    menu = models.ForeignKey('Menu',
                             on_delete=models.CASCADE,
                             related_name='items',
                             )
    parent = models.ForeignKey('self',
                               on_delete=models.CASCADE,
                               related_name='subitems',
                               blank=True,
                               null=True,
                               )
    name = models.CharField(max_length=255)
    target = models.CharField(max_length=255,
                              blank=True,
                              null=True
                              )
    separator = models.BooleanField(default=False)

    def __str__(self):
        """String representation of MenuItem."""
        return self.name

    def get_absolute_url(self):
        """Get the absolute url of MenuItem target."""
        target, _, args = self.target.partition(';')
        args = re.split(';', args) if args else []
        kwargs = {}
        for arg in args:
            key, value = re.split('=', arg)
            kwargs[key] = value
        try:
            url = reverse(target, kwargs=kwargs)
        except NoReverseMatch:
            url = self.target or '#'
        return url

djangopress/pages/models.py
"""Page models."""
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models


@python_2_unicode_compatible
class Page(models.Model):
    """Page model."""
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        """String representation of Page."""
        return self.title

djangopress/blog/views.py
"""Views for djangopress"""
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.dates import MonthArchiveView

from djangopress.core.models import Option

from .models import Post


class PostList(ListView):  # pylint:disable=too-many-ancestors
    """Home view."""
    model = Post
    context_object_name = 'posts'

    @staticmethod
    def get_paginate_by(queryset):
        posts, _ = Option.objects.get_or_create(name='posts_per_page',
                                                defaults={'value': '5'}
                                                )
        try:
            number_of_post = int(posts.value)
        except ValueError:
            number_of_post = 5
        return number_of_post


class PostDetail(DetailView):  # pylint: disable=too-many-ancestors
    """Post view."""
    model = Post


class MonthArchive(MonthArchiveView):  # pylint: disable=too-many-ancestors
    """Month archive view."""
    model = Post
    month_format = '%m'
    date_field = 'creation_date'
    context_object_name = 'posts'

djangopress/pages/views.py
"""Views for Djangopress Pages."""
from django.views.generic.detail import DetailView

from .models import Page


class PageDetail(DetailView):  # pylint: disable=too-many-ancestors
    """Page view."""
    model = Page

djangopress/blog/templates/blog/includes/posts_list.html
{% load blog_tags djangopress_tags %}
{% for post in posts %}
<div class="blog-post" id="post-{{ post.pk }}">
  {% with post_url=post.get_absolute_url %}
    <h2 class="blog-post-title">
      <a href="{{ post_url }}">{{ post.title|safe }}</a>
    </h2>
    <p class="blog-post-meta">
      <span class="glyphicon glyphicon-calendar"></span>
      {{ post.creation_date.date }} by 
      <span class="glyphicon glyphicon-user"></span>
      {{ post.author }}
    </p>
    <div class="entry clearfix">
      {{ post.content|more:post_url|linebreakshtml }}
    </div>
  {% endwith %}
</div>
{% endfor %}

djangopress/blog/templates/blog/post_archive_month.html
{% extends 'djangopress/base.html' %}


{% block content %}
<div class="col-sm-8">  
  <h2>{{ month|date:'F Y'}}</h2>
  {% include 'djangopress/includes/posts_list.html' with posts=posts %}
</div>
{% endblock %}

djangopress/blog/templates/blog/post_detail.html
{% extends 'djangopress/base.html' %}
{% load djangopress_comments %}

{% block head %}
  {% with title=post.title|striptags|add:" - "|add:settings.title %}
    {{ block.super }}
  {% endwith %}
{% endblock %}

{% block content %}
<div class="col-sm-8 blog-main">
  <div class="blog-post" id="{{ post.pk }}">
    <h2 class="blog-post-title">{{ post.title|safe }}</h2>
    <p class="blog-post-meta">
      <span class="glyphicon glyphicon-calendar"></span>
      {{ post.creation_date.date }} by 
      <span class="glyphicon glyphicon-user"></span>
      {{ post.author }}
    </p>
    <div class="entry clearfix">
        {{ post.content|safe }}
    </div>
    <p class="blog-post-meta">
      <span class="glyphicon glyphicon-folder-open"></span>
      Posted in {{ post.category }} <strong> | </strong>
      <span class="glyphicon glyphicon-comment"></span>
      {% if post.comment_set.count %}
        {{ post.comment_set.count }} Comment{{ post.comment_set.count|pluralize }}
      {% else %}
        No Comments
      {% endif %}
      <hr>
    </p>
    <div id="comments" class="comments-area">
      {% show_comments post %}
    </div>
  </div>
</div>
{% endblock %}

djangopress/blog/templates/blog/post_list.html
{% extends 'djangopress/base.html' %}

{% block content %}
<div class="col-sm-8 blog-main">
  {% include 'blog/includes/posts_list.html' with posts=posts %}
  {% if is_paginated %}
    <nav>
      <ul class="pager">
        {% if page_obj.has_previous %}
          <li>
            <a href="{% url 'djangopress:page' page=page_obj.previous_page_number %}">
              Previous
            </a>
          </li>
        {% endif %}
        {% if page_obj.has_next %}
          <li>
            <a href="{% url 'djangopress:page' page=page_obj.next_page_number %}">
              Next
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
  </div>
{% endblock %}

djangopress/blog/templates/blog/tags/archive_list.html
<h4>Archives</h4>
<ol class="list-unstyled">
  {% for year, months in years.items %}
    {% for month in months %}
      <li><a href="{% url 'djangopress:month_archive' year=month.year month=month.month %}">{{ month|date:'F Y' }}</a></li>
    {% endfor %}
  {% endfor %}
</ol>

djangopress/blog/templates/blog/tags/category_list.html
<h4>Categories</h4>
<ol class="list-unstyled">
  {% for category in categories %}
    <li>{{ category }}</li>
  {% endfor %}
</ol>

djangopress/blog/templates/blog/tags/recent_posts.html
<h4>Recent posts</h4>
<ol class="list-unstyled">
  {% for post in posts %}
    <li><a href="{{ post.get_absolute_url}}">{{ post|safe }}</a></li>
  {% endfor %}
</ol>

djangopress/comments/templates/comments/tags/comments_list.html
{% load djangopress_tags %}
<ol class="comment-list">
  {% for comment in comments %}
    <li class="comment {% cycle 'even' 'odd' %}">
      <article>
        <header class="comment-meta">
          <cite>{{ comment.author }}</cite>
          <span class="glyphicon glyphicon-calendar"></span>
          {{ comment.creation_date}}
        </header>
        <section class="comment-content comment">
          {{ comment.content|linebreakshtml }}
        </section>
        <hr>
      </article>
    </li>
  {% endfor %}
</ol>

djangopress/comments/templates/comments/tags/recent_comments.html
<h4>Recent Comments</h4>
<ol class="list-unstyled">
  {% for comment in comments %}
    <li>
      {{ comment.author }} on
      <a href="{{ comment.post.get_absolute_url}}">
          {{ comment.post}}
      </a>
    </li>
  {% endfor %}
</ol>

djangopress/menus/templates/menus/tags/menu.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        {% for item in menu_items %}
          {% if item.show_dropdown %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                   role="button" aria-haspopup="true" aria-expanded="false">
                     {{ item }} <span class="caret"></span>
                </a>
              <ul class="dropdown-menu">
                {% for subitem in item.subitems.all %}
                  {% if subitem.separator %}
                    <li role="separator" class="divider"></li>
                  {% else %}
                    <li><a href="{{ subitem.get_absolute_url }}">{{ subitem }}</a></li>
                  {% endif %}
                {% endfor %}
              </ul>
            </li>
          {% else %}
            <li><a href="{{ item.get_absolute_url }}">{{ item }}</a></li>
          {% endif %}
        {% endfor %}
      </ul>
    </div>
  </div>
</nav>

djangopress/pages/templates/pages/page_detail.html
{% extends 'djangopress/base.html' %}

{% block head %}
  {% with title=page.title|striptags|add:" - "|add:settings.title %}
    {{ block.super }}
  {% endwith %}
{% endblock %}

{% block content %}
<div class="col-sm-8 blog-main">
  <div class="blog-post" id="{{ page.pk }}">
    <h2 class="blog-post-title">{{ page.title|safe }}</h2>
    <div class="page clearfix">
        {{ page.content|safe }}
    </div>
  </div>
</div>
{% endblock %}

djangopress/templates/djangopress/base.html
{% spaceless %}<!DOCTYPE html>
<html{% if LANGUAGE_CODE %} lang="{{ LANGUAGE_CODE }}"{% endif %}>
  <head>
    {% with title=settings.title %}
      {% block head %}
        {% include 'djangopress/head.html' %}
      {% endblock %}
    {% endwith %}
  </head>
  <body>
    {% block menu %}
      {% with menu_name='Main' %}
        {% include 'djangopress/menu.html' %}
      {% endwith %}
    {% endblock %}
    {% block header %}
      {% include 'djangopress/header.html' %}
    {% endblock %}
    <div class="container">
      <div class="row">
        {% block content %}
        {% endblock %}
        {% block sidebar %}
          {% include 'djangopress/sidebar.html' %}
        {% endblock %}
      </div>
    </div>
    <footer class="blog-footer">
      {% block footer %}
        {% include 'djangopress/footer.html' %}
      {% endblock %}
    </footer>
    {% block scripts %}
      {% include 'djangopress/scripts.html' %}
    {% endblock %}
  </body>
</html>
{% endspaceless %}

djangopress/templates/djangopress/footer.html
<p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
<p>
  <a href="#">Back to top</a>
</p>

djangopress/templates/djangopress/head.html
{% load staticfiles %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{{ tagline }}">
<meta name="author" content="">

<title>{{ title }}</title>

<!-- Bootstrap core CSS -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{% static 'style.css' %}" rel="stylesheet">

djangopress/templates/djangopress/header.html
<div class="blog-header">
  <div class="container">
      <h1 class="blog-title">
        <a href="{% url "djangopress:home" %}">{{ settings.title }}</a>
      </h1>
    <p class="lead blog-description">{{ settings.tagline }}</p>
  </div>
</div>

djangopress/templates/djangopress/menu.html
{% load menu_tags %}
{% menu menu_name %}

djangopress/templates/djangopress/scripts.html
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

djangopress/templates/djangopress/sidebar.html
{% load blog_tags %}
{% load djangopress_comments %}
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
  <div class="sidebar-module">
    <div class="input-group custom-search-form">
      <input type="text" class="form-control">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">
	  <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
  </div>
  <div class="sidebar-module">
    {% archive_list %}
  </div>
  <div class="sidebar-module">
    {% recent_comments %}
  </div>
  <div class="sidebar-module">
    {% category_list %}
  </div>
  <div class="sidebar-module">
    {% recent_posts %}
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="#">GitHub</a></li>
      <li><a href="#">Twitter</a></li>
      <li><a href="#">Facebook</a></li>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->